apiVersion: v1
kind: Service
metadata:
  name: temperaturas-frontend-svc
  labels:
    app: temperaturas-frontend
spec:
  ports:
    - port: 80
      targetPort: 3007
  selector:
    app: temperaturas-frontend
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperaturas-frontend-deploy
  labels:
    app: temperaturas-frontend
spec:
  selector:
    matchLabels:
      app: temperaturas-frontend
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: temperaturas-frontend
        tier: frontend
    spec:
      containers:
      - name: temperaturas-frontend
        image: blancaclaire/sanvalero:daw-front
        imagePullPolicy: Always
        ports:
        - containerPort: 3007
        env:
        - name: TEMP_SERVER
          value: "temperaturas-backend-svc:5000"
